### ISSUE TITLE
Unable to reply to inital homey interface message

### ISSUE THREAD

**Issue by ericwegener** [Joolee/nl.joolee.homey.sms#1]
During the app configuration, I can get through all steps except the end one. When i use the homey interface to send the "Please reply to this test message!" from inbox, it comes up on my phone with a 4 digit phone number which I cannot reply to (I assume messagebird defaults to the 'Originator' instead of the Shard VMN. I can get the phone number to reply back by using messagebird ,but then homey cannot see these received messages (I assume because it does not contain 'inbox').

In answer to your questions:
1) Did you configure (at least) the VMN on the MessageBird config panel to forward messages to Homey? 
         -Yep
                    (the picture doesn't have the entire web address but I copied it exactly as:
                   "https://webhooks.athom.com/webhook/undefined/?homey=PgU4RS4rHAPGHyTEVsFN9/VxQisqzUh5Fiw4wpv43WI"

2) And when you sent the 'please reply to..' message, did you leave the 'sender name' field set to inbox?
      -Yep

 
I'll show the transcript from messagebird: 

The homey interface sends it as this Originator 'Eric' which is a 4 number phone number which i cannot reply to:

But I can reply to the shared VMN that message bird sends:

Could this be a country specific thing? As I am in Australia this 4 digit number i can't reply to might be set as default for Australia?

Again many many thanks for you skills in developing this, and perfect instruction details.
        Eric

**Comment by Joolee** [comment]
I spotted at least two errors on my side. I forgot to include the webhook url correctly when I submitted the app to the store. This is fixed in version 1.0.1 (as soon as it hits the store.) You will need to copy-paste the url to MessageBird again. (the 'undefined' part in the URL should be '58482af88945ce960d6bdadd')
You can fix the URL already but you do need 1.0.1 before Homey can actually receive messages from MessageBird.

The other issue is from a lack of decent testing :( The 'Sender name' value in the test message will be overwritten by the default 'Sender name' you set in the 'Sending messages' section of the configuration. You appearently set that to Eric :P
I also fixed this in V1.0.1

Do note that when you set the default sender name to anything other than blank or 'inbox', this will be used by Homey to send messages from flows. As you have seen, you cannot reply to these messages.

Also, you might want to remove the API web address you pasted and your phone numbers from your post. Both can be misused by readers to send messages to your Homey or your phone ;)

**Comment by ericwegener** [comment]
Brilliant!!! 
         Many many thanks for your genius work. I will eagerly await v1.0.1  and will update the url. 
  
Again wow, speedy fix,  many many thanks.  Lol, and thanks for the advice, I'll remove my  personal information 🤦‍♂️ .  

Your skills are really appreciated 🙌

**Comment by Joolee** [comment]
Version 1.0.1 is now available in the store
